spring.mongodb.uri=mongodb://mongodb:27017/report_db
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:hackaton-reports-soat-6jneli}
aws.s3.base-url=https://${AWS_S3_BUCKET_NAME:hackaton-reports-soat-6jneli}.s3.${AWS_REGION:us-east-1}.amazonaws.com
aws.sqs.status-update-queue-url=${AWS_SQS_STATUS_UPDATE_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/481824691194/diagram-status-update}