spring.application.name=hackaton-report-api
spring.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/report_db}
spring.data.mongodb.auto-index-creation=true

server.port=8080

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:hackaton-reports-soat-6jneli}
aws.s3.base-url=${AWS_S3_BUCKET_NAME:hackaton-reports-soat-6jneli}
aws.sqs.status-update-queue-url=${AWS_SQS_STATUS_UPDATE_QUEUE_URL:https://sqs.us-east-1.amazonaws.com/481824691194/diagram-status-update}

app.base-url=${APP_BASE_URL:http://localhost:8080}
management.info.build.enabled=true
management.endpoints.web.base-path=/api/reports/actuator
aws.access-key-id: ${AWS_ACCESS_KEY_ID}
aws.secret-access-key: ${AWS_SECRET_ACCESS_KEY}
aws.session-token: ${AWS_SESSION_TOKEN}
