spring.mongodb.uri=mongodb://mongodb:27017/report_db
aws.endpoint-override=http://localstack:4566
aws.s3.bucket-name=reports-bucket
aws.s3.base-url=http://localhost:4566/reports-bucket
aws.sqs.status-update-queue-url=http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/status-update-queue
