spring.application.name=hackaton-report-api
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/report_db}
spring.data.mongodb.auto-index-creation=true

server.port=8080

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
