apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-api-deployment
  namespace: default
  labels:
    app: report-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: report-api
  template:
    metadata:
      labels:
        app: report-api
    spec:
      serviceAccountName: report-sa
      containers:
        - name: report-api
          image: <ECR_REGISTRY>/hackaton-report-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: report-secrets
                  key: MONGODB_URI
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: report-secrets
                  key: AWS_REGION
            - name: AWS_S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: report-secrets
                  key: AWS_S3_BUCKET_NAME
            - name: AWS_SQS_STATUS_UPDATE_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: report-secrets
                  key: AWS_SQS_STATUS_UPDATE_QUEUE_URL
            - name: APP_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: report-secrets
                  key: APP_BASE_URL
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
